/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 20-sept.-2023 4:52:52 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Categoria CASCADE
;

DROP TABLE IF EXISTS Clientes CASCADE
;

DROP TABLE IF EXISTS Productos CASCADE
;

DROP TABLE IF EXISTS Proveedor CASCADE
;

DROP TABLE IF EXISTS Venta_Producto CASCADE
;

DROP TABLE IF EXISTS Ventas CASCADE
;

/* Create Tables */

CREATE TABLE Categoria
(
	codCategoria integer NOT NULL,
	nombreCategoria varchar(50) NOT NULL
)
;

CREATE TABLE Clientes
(
	cedula integer NOT NULL,
	nombre varchar(100) NOT NULL
)
;

CREATE TABLE Productos
(
	codProducto integer NOT NULL,
	nombre varchar(30) NOT NULL,
	precioUnitario numeric(10,2) NOT NULL,
	codCategoria integer NOT NULL,
	codProveedor integer NOT NULL
)
;

CREATE TABLE Proveedor
(
	codProveedor integer NOT NULL,
	nombreProveedor varchar(50) NOT NULL
)
;

CREATE TABLE Venta_Producto
(
	codVenta integer NOT NULL,
	codProducto integer NOT NULL,
	cantidadVendida integer NOT NULL,
	codVentaProducto integer NOT NULL
)
;

CREATE TABLE Ventas
(
	codVenta integer NOT NULL,
	fecha date NOT NULL,
	valorTotal numeric(12,2) NOT NULL,
	cedula integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Categoria ADD CONSTRAINT PK_Categoria
	PRIMARY KEY (codCategoria)
;

ALTER TABLE Clientes ADD CONSTRAINT PK_Clientes
	PRIMARY KEY (cedula)
;

ALTER TABLE Productos ADD CONSTRAINT PK_Productos
	PRIMARY KEY (codProducto)
;

CREATE INDEX IXFK_Productos_Categoria ON Productos (codCategoria ASC)
;

CREATE INDEX IXFK_Productos_Proveedor ON Productos (codProveedor ASC)
;

ALTER TABLE Proveedor ADD CONSTRAINT PK_Proveedor
	PRIMARY KEY (codProveedor)
;

ALTER TABLE Venta_Producto ADD CONSTRAINT PK_Venta_Producto
	PRIMARY KEY (codVentaProducto)
;

CREATE INDEX IXFK_Venta_Producto_Productos ON Venta_Producto (codProducto ASC)
;

CREATE INDEX IXFK_Venta_Producto_Ventas ON Venta_Producto (codVenta ASC)
;

ALTER TABLE Ventas ADD CONSTRAINT PK_Ventas
	PRIMARY KEY (codVenta)
;

CREATE INDEX IXFK_Ventas_Clientes ON Ventas (cedula ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Productos ADD CONSTRAINT FK_Productos_Categoria
	FOREIGN KEY (codCategoria) REFERENCES Categoria (codCategoria) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Productos ADD CONSTRAINT FK_Productos_Proveedor
	FOREIGN KEY (codProveedor) REFERENCES Proveedor (codProveedor) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Venta_Producto ADD CONSTRAINT FK_Venta_Producto_Productos
	FOREIGN KEY (codProducto) REFERENCES Productos (codProducto) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Venta_Producto ADD CONSTRAINT FK_Venta_Producto_Ventas
	FOREIGN KEY (codVenta) REFERENCES Ventas (codVenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Ventas ADD CONSTRAINT FK_Ventas_Clientes
	FOREIGN KEY (cedula) REFERENCES Clientes (cedula) ON DELETE No Action ON UPDATE No Action
;
